apiVersion: v1
entries:
  airbyte:
  - apiVersion: v2
    appVersion: 0.36.0-alpha
    created: "2022-04-16T11:49:03.313725+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.x.x
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 7.x.x
    description: Helm chart to deploy airbyte
    digest: 0984086cbf82be1a65681543e9ca92024d2449a84245fe80094ec2a5b96a352f
    name: airbyte
    type: application
    urls:
    - airbyte-0.3.1.tgz
    version: 0.3.1
generated: "2022-04-16T11:49:03.307079+02:00"
